import { mapTileDefaultAttributes } from "../../common/constants";
import { MapTileVariant, PixelSize } from "../../common/types";

export const tileVariants: MapTileVariant[] = [
  "column",
  "column_wall",
  "wall_fountain_mid_blue",
  "wall_fountain_mid_red",
  "wall_fountain_basin_red",
  "wall_fountain_basin_blue",
  "wall_goo_base",
  "wall_goo",
  "wall_hole_1",
  "wall_hole_2",
  "wall_banner_blue",
  "wall_banner_red",
  "wall_banner_green",
  "wall_banner_yellow",
  "floor_ladder",
  "floor_spikes",
  "hole",
  "floor_stairs",
  "floor_1",
  "floor_2",
  "floor_3",
  "floor_4",
  "floor_5",
  "floor_6",
  "floor_7",
  "floor_8",
  "wall_left",
  "wall_mid",
  "wall_right",
  "wall_top_left",
  "wall_top_mid",
  "wall_top_right",
  "button_red_up",
  "button_red_down",
  "button_blue_up",
  "button_blue_down",
  "lever_left",
  "lever_right",
  "doors_frame_left",
  "doors_frame_right",
  "doors_frame_top",
  "doors_leaf_closed",
  "doors_leaf_open",
  "wall_edge_bottom_left",
  "wall_edge_bottom_right",
  "wall_edge_mid_left",
  "wall_edge_top_left",
  "wall_edge_left",
  "wall_edge_top_right",
  "wall_edge_right",
  "wall_edge_mid_right",
  "wall_edge_tshape_bottom_right",
  "wall_edge_tshape_bottom_left",
  "wall_edge_tshape_right",
  "wall_edge_tshape_left",
  "wall_outer_front_right",
  "wall_outer_front_left",
  "wall_outer_mid_left",
  "wall_outer_top_left",
  "wall_outer_top_right",
  "wall_outer_mid_right",
  "wall_fountain_top_1",
  "wall_fountain_top_2",
  "wall_fountain_top_3",
];

export const variantSizes: Record<string, PixelSize> = {
  column: mapTileDefaultAttributes.column.size,
  column_wall: mapTileDefaultAttributes.column_wall.size,
  doors_frame_left: mapTileDefaultAttributes.doors_frame_left.size,
  doors_frame_right: mapTileDefaultAttributes.doors_frame_right.size,
  doors_frame_top: mapTileDefaultAttributes.doors_frame_top.size,
  doors_leaf_closed: mapTileDefaultAttributes.doors_leaf_closed.size,
  doors_leaf_open: mapTileDefaultAttributes.doors_leaf_open.size,
};

export const gap = 2;
